package org.envaya.sms;

import android.net.Uri;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

public class MmsPart {
    private App app;
    private long partId;
    private String contentType;
    private String name;
    private String text;
    private String cid;
    private String dataFile;
    
    public MmsPart(App app, long partId)
    {
        this.app = app;
        this.partId = partId;
    }

    /*
     * The part id is the local value of the _id column in the MMS part table
     * (see android.provider.Telephony.Part)
     */
    public long getPartId()
    {
        return partId;
    }
    
    /*
     * The content id of a MMS part is used to resolve references in SMIL
     * like <img region="Image" src="cid:805"/> . Telephony.java claims
     * that the cid column is an integer, but it is actually a string
     * like "<0000>" or "<83>".
     */    
    public void setContentId(String cid)
    {
        this.cid = cid;
    }
    
    public String getContentId()
    {
        return cid;
    }
    
    /*
     * Common Content-Type values for MMS parts include:
     *  application/smil
     *  text/plain
     *  image/jpeg 
     */
    public void setContentType(String contentType)
    {
        this.contentType = contentType;
    }
    
    public String getContentType()
    {
        return contentType;
    }    
        
    /*
     * The name of an MMS part is the filename of the original file sent
     * (e.g. Image001.jpg). For text/SMIL parts, the filename is generated by the
     * sending phone and can usually be ignored.
     */    
    public void setName(String name)
    {
        this.name = name;
    }       
    
    public String getName()
    {
        return name;
    }
        
    /* 
     * The text is the content of text-based MMS parts (application/smil,
     * text/plain, or text/html), and is null for multimedia parts.
     */
    public void setText(String text)
    {
        this.text = text;
    }
           
    public String getText()
    {
        return text;
    }    
    
    public void setDataFile(String dataFile)
    {
        this.dataFile = dataFile;
    }
    
    public String getDataFile()
    {
        return dataFile;
    }
    
    public long getDataLength()
    {
        if (dataFile != null)
        {
            return new File(dataFile).length();
        }
        else
        {
            return -1;
        }
    }
    
    public byte[] getData() throws IOException
    {
        int length = (int)getDataLength();
        byte[] bytes = new byte[length];

        int offset = 0;
        int bytesRead = 0;

        InputStream in = openInputStream();

        while (offset < bytes.length) 
        {                 
            bytesRead = in.read(bytes, offset, bytes.length - offset);

            if (bytesRead < 0)
            {
                break;
            }

            offset += bytesRead;
        }

        in.close();
        
        if (offset < bytes.length)
        {
            throw new IOException("Failed to read complete data of MMS part");
        }
        
        return bytes;
    }
    
    /* 
     * For multimedia parts, the _data column of the MMS Parts table contains the
     * path on the Android filesystem containing that file, and openInputStream
     * returns an InputStream for this file.
     */
    public InputStream openInputStream() throws FileNotFoundException
    {
        return app.getContentResolver().openInputStream(getContentUri());
    }
    
    
    @Override
    public String toString()
    {
        return "part " + partId + ": " + contentType + "; name=" + name + "; cid=" + cid;
    }                
        
    public Uri getContentUri()
    {
        return Uri.parse("content://mms/part/" + partId);        
    }
    
}
